# Generated by Django 5.0.3 on 2024-03-27 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_estoque', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='Estado',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='Cep',
            new_name='zipcode',
        ),
    ]
