# Generated by Django 5.0.3 on 2024-03-28 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_estoque', '0002_rename_estado_record_state_rename_cep_record_zipcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='cidade',
            new_name='Loja_Cod_Loja',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='endereco',
            new_name='QTD_estoque',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='email',
            new_name='descricao',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='nome',
            new_name='fornecedor',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='zipcode',
            new_name='locacao',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='sobrenome',
            new_name='nome_produto',
        ),
        migrations.RemoveField(
            model_name='record',
            name='state',
        ),
        migrations.RemoveField(
            model_name='record',
            name='telefone',
        ),
    ]
